POST http://127.0.0.1:5000/recommend 
Content-Type: application/json

    {
    "Year": 2020, 
    "Price": 35000,
    "Mileage": 15000, 
    "Color": "Blue", 
    "Transmission": "Automatic", 
    "Type": "Truck"
    }
